type Candle {
    openTime: String
    open: String
    high: String
    low: String
    close: String
    volume: String
    closeTime: String
    quoteVolume: String
    trades: Int
    baseAssetVolume: String
    quoteAssetVolume: String
}
type Ticker {
    eventType: String
    eventTime: Int
    symbol: String
    priceChange: String
    priceChangePercent: String
    weightedAvg: String
    prevDayClose: String
    curDayClose: String
    closeTradeQuantity: String
    bestBid: String
    bestBidQnt: String
    bestAsk: String
    bestAskQnt: String
    open: String
    high: String
    low: String
    volume: String
    volumeQuote: String
    openTime: Int
    closeTime: Int
    firstTradeId: Int
    lastTradeId: Int
    totalTrades: Int
}

type Query {
    candles(symbol: String!): [Candle!]
}
type Subscription {
    ticker(symbols: [String]!): Ticker!
}
